### ISSUE TITLE
daewooforum.pl

### ISSUE THREAD

**Issue by gargaamel** [gargaamel/polskie-ciasteczka-rodo-zgloszenia#14]
ciasteczka

![ss206](https://user-images.githubusercontent.com/44813765/49342848-7ed54700-f660-11e8-962d-673cd035bdef.png)

<details not-open>
<summary>Problem występuje nawet przy włączonych:</summary>

- lista Polskie Filtry RODO-Ciasteczkowe + 
dodatek Polska Zgoda Ciasteczkowa
- dodatek I don't care about cookies
- lista Fanboy’s Cookiemonster List

</details>

**Comment by krystian3w** [comment]
`#?#.back > table:-abp-has(a[href="javascript:location.reload(true)"])`

Chyba takie coś może być, `nth-of-type`, dobrze nie zabezpieczy.

**Comment by gargaamel** [comment]
Chyba tak wystarczy `##.back > table:not(.bodyline)`

<details not-open>
<summary>Jeszcze zauważyłem tam komunikat RODO, który jest domyśłnie rozwinięty:</summary>

![ss208](https://user-images.githubusercontent.com/44813765/49343327-39684800-f667-11e8-8ec6-e014ff460f33.png)

</details>
.
<details not-open>
<summary>ale się zwija po kliknięciu w belkę "ogłoszenie"</summary>

![ss209](https://user-images.githubusercontent.com/44813765/49343335-53a22600-f667-11e8-9a88-581a2a65166a.png)

</details>
.

Więc na te RODO może by dać coś żeby domyślnie było zwinięte np:
`daewooforum.pl###hm:style(position: relative !important; display: none !important;)`
`daewooforum.pl###hm2:style(display: inline !important; position: relative !important;)`

Tylko, że, wtedy:
-  się nie rozwija
- i może by  dodać jakieś `:has` albo `:has-text` dla pewności żeby chowało tylko komunikat RODO a nie każdy inny np.  `daewooforum.pl###hm:has(.gem):style(position: relative !important; display: none !important;)` ale coś to nie działa, bo nawet nie orientuję się czy można tak łączyć `:has` i `:style`

**Comment by krystian3w** [comment]
daewooforum.pl##.back > table:not(.bodyline):nth-of-type(1)

Na pewno będzie szybsze od sprawdzania tekstów czy elementów wewnątrz.

---

A ogłoszenie skoro da się tylko zwinąć to bym nie ruszał, może kiedyś coś innego tam wstawiom i będzie drugie zarabiam z wycinam inem jakiegoś `td` i `center`.

**Comment by gargaamel** [comment]
> krystian3w : A ogłoszenie skoro da się tylko zwinąć 

Da się zwijać i rozwijać, a na moich filtrach, jest zwinięte i nie da się rozwinąć, ale nie twierdzę, że się nie da tego zrobić tak, żeby dało się rozwijać, po prostu mi się nie udało, może tobie się uda.

**Comment by krystian3w** [comment]
Można by sprawdzić czy `:hover` nadpisuje ale to już niestety raczej nie na poziom RODO-ciasteczkowej (nie my coś popsuliśmy by poprawiać wygląd strony - np. fix-y social).

**Comment by krystian3w** [comment]
```css
daewooforum.pl#$#hm[style="position: relative; display: inline;"] .row1 {display: none !important;}
daewooforum.pl#$#hm[style="position: relative; display: none;"] {display: block !important;}
daewooforum.pl###hm2
```

**Comment by krystian3w** [comment]
```css
daewooforum.pl#$##hm[style="position: relative; display: inline;"] .row1 {display: none !important;}
daewooforum.pl#$##hm[style="position: relative; display: none;"] {display: block !important;}
daewooforum.pl#$##hm2
```

Niby działa, ale raczej pod może własną listę.
